version: '3'

volumes: 
  redis_data:

services: 
  redis-master:
    image: 'bitnami/redis:5.0'
    ports: 
      - '7370:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=cd4f6a378c0b
    volumes:
      - redis_data:/bitnami/redis/data
    restart: always
    healthcheck:
      test: "exit 0"
  redis-slave-1:
    image: 'bitnami/redis:5.0'
    ports:
      - '16379:6379'
    restart: always
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=cd4f6a378c0b
      - REDIS_PASSWORD=33dd00ad0c5f
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=master:redis-master:6379:1:cd4f6a378c0b,slave-1:redis-slave-1:6379:1:33dd00ad0c5f
    ports:
    - "8081:8081"